monta-app/github-workflows

.github/workflows/build.yaml, .github/workflows/deploy.yaml, .github/workflows/test.yaml
* also sneaked in a workflow file for usage in pull_requests
=> fix: Change build hosts to github ubuntu-latest

.github/workflows/deploy.yaml
=> feat: include service name and stage in commit message

.github/workflows/deploy.yaml
Need to think about how to update the workflow without breaking existing workflows.
Tag, for example.
=> feat(v2): Adapt workflow to use AWS OIDC DEVOPS-154

.github/workflows/it-test.yaml
Simplified the IT tests workflow so it uses the action file from the repo, to avoid cross maintenance
=> chore: Simplified the IT tests workflow

.github/workflows/deploy.yaml
Add a step to update commit hashes ([here](https://github.com/monta-app/kube-manifests/blob/6bf13c4c6cf1c7b4e7c5e354a48b0a55bc9b48f0/apps/admin-panel/dev/cluster/config.yaml#L6-L7)) in order to update source code diff link properly.
=> feat: add a step to update hashes

.github/workflows/deploy.yaml
of all the pedantic native English speaking people in the company I would have expected @BrianEstrada to know the rules for plurals in the English language
=> fix: Fixing the openapi pushing

.github/workflows/deploy.yaml
Tested:
- complete workflow
- builds with/without correctly according to arm build flag
- sends slack messages
- creates correct manifest
=> Self hosted runner pods

.github/workflows/deploy.yaml
instead of deploying by committing to kube-manifests
=> add optional deploy by argocd cli

.github/workflows/deploy.yaml
Reverts monta-app/github-workflows#62
=> Revert "argocd multiple sources"

.github/workflows/deploy.yaml
Add another login step so we also log into the ecr on internal
=> fix(build): log into multiple ecr

.github/workflows/deploy.yaml
This might fix the random teleport crashes
=> feat(teleport): Upgrade teleport version to 15.3.7

.github/workflows/deploy.yaml, .github/workflows/it-test.yaml, .github/workflows/pull-request-kover.yaml
Extension to https://github.com/monta-app/github-workflows/pull/88 but applied to all artifact uploads
=> fix: overwrite test artifacts

docker-gradle-setup/action.yml, gradle-post-build/action.yml
Remove the explicit cache save and restore in favor of setup-java's `cache: 'gradle'`
=> feat: streamline caching

.github/workflows/deploy.yaml
sends the `name` and `tag` in the payload (no `helmValue` or `repository` as discussed with Jonas)
=> deploy webhook in infra-portal

README.md
This updates README for release automation workflow.
=> chore: update readme (PS-442)

.github/workflows/deploy.yaml
This should read the backstage catalog file in the project and set the values from that. Otherwise we just default set it to SRE.
=> feat(backstage): set correct owner and system of openapi docs on backstage

.github/workflows/deploy.yaml
Similar to https://github.com/monta-app/server/pull/15137/files
=> fix: Update webhook as old was invalidated

docker-gradle-setup/action.yml
New option `skip-gradle-validation` in the docker-gradle-setup action.
=> feat: new option skip-gradle-validation in docker-gradle-setup

.github/workflows/deploy.yaml
Having trouble reading env, directly put version in command
=> fix(deploy): directly use k8s version

.github/workflows/deploy.yaml
Reverts monta-app/github-workflows#132
Seems we can't figure out the conditionals / needs and have all our custom setups work properly
context: https://monta-app01.slack.com/archives/C02NQ35QS8Z/p1745407817214869
=> Revert "chore: clean up if conditions again"
