- .github/workflows/deploy.yaml
Examples should not include the `service-` prefix, as that would deploy to wrong path in kube-manifests.
> chore: update description for "service-identifier" parameter

- .github/workflows/deploy.yaml
Support easy switch between static keys and assumed role.
This way, we won't broke any existing workflows and it is easier for us to switch back to static keys if needed.
- When `secrets.AWS_ACCOUNT_ID` is given, use the step `Configure AWS credentials via assumed role` and skip step `Configure AWS credentials`. [Example workflow run](https://github.com/monta-app/service-cpi-api/actions/runs/4566085533/jobs/8059204702).
- If `secrets.AWS_ACCOUNT_ID` is not given, the other way around. [Example workflow run](https://github.com/monta-app/service-cpi-api/actions/runs/4566169018/jobs/8058970505).
> feat(v2): Allow use static keys or assumed role

- .github/workflows/deploy.yaml
Remove github context pass-on to eliminate "argument list too long" shell error in slack-notificer-cli-action due to huge environment data passed. Relates to https://github.com/monta-app/slack-notifier-cli-action/pull/4 and https://github.com/monta-app/slack-notifier-cli/pull/43.
Also add configurable slack channel with default to previous hardcoded value (the "deployment" channel)
> fix: argument list too long

- .github/workflows/deploy.yaml
Think we could just remove ns from service profile. The resource will be deployed to the same namespace where the service is anyway.
> fix: remove namespace from service profile

- .github/workflows/deploy.yaml
To ensure that hashes aren't going to be interpreted as numbers during diff-link generation, we cast the hashes to strings.
Based on the work done by @HotThoughts in https://github.com/monta-app/server/pull/9926
> fix: cast commit hashes to strings

- .github/workflows/deploy.yaml
- Mostly in order to save money instead of having multiple short running jobs that cost a lot of money
- Renamed `init_message` to `init`
- Same job produces both outputs
- Every job that needs to send a slack message needs `init` in order to get the message ID. Easier to have one line with the same value, instead of having different dependent needs with the same value
- In addition, every job doesn't need to `output` the slack message ID anymore
- The `update_build_fail` didn't run in some cases, depends on the specific workflow
- Created two explicit success and fail jobs to update the build status, making sure it always runs
- Will update fail status if couldn't push manifest to ECR as a conditional step
- The `deploy` message **ends** at `deploy_by_*`
> restructure

- .github/workflows/deploy.yaml
- set dynamically based on `stage` input
- needed only when the token secret is set
- if going to deploy by ArgoCD (instead of committing to kube-manifests) or if going to update OpenAPI spec, verify that the token exists
- Gets variables needed by ArgoCD instead of reading from files. Super important for the multi-repo setup
- Uses Teleport to authenticate
- applies directly to k8s, no need to push to git
Requires all repos that currently use `upload-open-api` to provide the `ARGOCD_TOKEN` secret.
I will open PRs for all the repos that use it, providing the secret and deleting the `service-profile.yaml` file from their directories https://github.com/monta-app/kube-manifests/pull/903
Progess:
> Update openapispec job to apply directly to the cluster

- .github/workflows/deploy.yaml
Adding ksp support so we can both use kapt and ksp annotation processors. Built it such that we can avoid an additional parameter so the build will just use whatever is available.
> feat(openapi): support ksp and kapt simultaneously (PS-216)

- .github/workflows/deploy.yaml
The list of tasks returned contains submodule tasks if run on the parent module. This will select the parent task (which comes first).
> fix(openapi): build parent if no gradle module set

- .github/workflows/deploy.yaml
Use case: we have a build where the openapi spec is produced in a service's submodule build directory but we want to run the top level build to also run the other submodules' tests.
This will find the spec in any subdirectory matching the target path so we are assuming there is only one spec per build generated, which I think is fair.
This should be backwards compatible as it considers multiple possible paths for the api spec including the single one it was considering before.
> feat(openapi): find spec in sub directories (PS-216)

- .github/workflows/deploy.yaml
Some builds require the environment variables to be present to be able to get a list of all available tasks.
For example: https://github.com/monta-app/service-i18n/actions/runs/7872965048/job/21479525846
> fix(openapi): Add GHL_ environment variables to task discovery

- .github/workflows/pull-request.yaml
In Charges, we would like to run the pull request workflow on every push to develop since we are not always doing PRs. Therefore, even though the workflow is named "pull-request" it would be great to have extra safety for the PR Title Checker job so that it only runs if actually in a PR context.
> fix: Only run pr title checker on pull request

- .github/workflows/it-test.yaml
Workflow fails on the step "Checkout PHP-Server" for example here: https://github.com/monta-app/partner-api/pull/1665
After development branch was deleted we can't use development as base-branch for php-server. Instead we should use staging branch as base branch.
> fix(portal2-api): Change php base branch to staging

- .github/workflows/deploy.yaml
Enforcing image tag to be a string
```
--helm-set-string stringArray                Helm set STRING values on the command line (can be repeated to set several values: --helm-set-string key1=val1 --helm-set-string key2=val2)
```
https://argo-cd.readthedocs.io/en/stable/user-guide/commands/argocd_app_set/
> fix(deploy): enforce string

- .github/workflows/deploy.yaml
PRevious would result in :
`The workflow is not valid. In .github/workflows/deploy_staging.yml (Line: 29, Col: 11): Error from called workflow monta-app/github-workflows/.github/workflows/deploy.yaml@v2 (Line: 324, Col: 13): Unrecognized named-value: 'secrets'. Located at position 1 within expression: secrets.TECHDOCS_AWS_ACCESS_KEY_ID != ''`
> fix(deploy): Fix bug with incorrect if statement

- .github/workflows/pull-request.yaml
* as the per the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) specification (which is unavailable right now) the way to mark a breaking change is by appending ! to commit type - examples
* `fix!:`
* `feat!:`
* decided to place it after the optional part `()`
* `fix(ocpp)!:`
* `feat(ocpp)!:`
> feat: Add support for ! (for marking breaking changes)

- .github/workflows/pull-request.yaml
See migration guide: https://github.com/actions/download-artifact/blob/main/docs/MIGRATION.md#overwriting-an-artifact
Should fix this: https://github.com/monta-app/partner-api/actions/runs/9580839702/job/26418822518?pr=1795
> fix: allow overwriting artifacts so actions can be re-run

- .github/workflows/pull-request.yaml
fix: use head of PR instead of target branch for tests
Currently it uses target branch for tests which can be super confusing, since you will see errors that are not reproducible locally (unless you merge with target already).
With this PR we are using the head commit fo the PR instead
> fix: use head of PR instead of target branch for tests

- docker-gradle-setup/action.yml
The gradle wrapper validation action [has a new path](https://github.com/gradle/wrapper-validation-action?tab=readme-ov-file).
> fix: new gradle validation action path

- .github/workflows/pull-request.yaml
Adds a test results report on pull requests.
Github action: https://github.com/EnricoMi/publish-unit-test-result-action
Context: https://monta-app01.slack.com/archives/C04JANZMTQV/p1721294268190129
> chore: add test results report for pull requests

- .github/workflows/pull-request-kover.yaml
- .github/workflows/pull-request.yaml
* workflow code also have rights to be simplified and not be duplicated :-) 
* this merges the pull-request.yaml and pull-request-kover.yaml into one parameterized file - I saw how they duplicated a lot of stuff and in different ways :-/
* this PR over in OCPP shows how to parameterize it https://github.com/monta-app/service-ocpp/pull/1593 - just set the coverage tool (defaults to jacoco) like this
```yaml
coverage-tool: kover
sonarcloud: true
```
* this updated version also supports the 'gradle-module' argument correctly again to build individual modules in multi-module projects.
> chore: parameterize pull request so it works with multiple coverage tools

- .github/workflows/deploy.yaml
The `service-cluster` and `service-namespace` outputs are only set when openapi spec is enabled, and I didn't anticipate ocpp-gateway disabling it.
WIth this, it's using the regular required inputs, and added a check for the `INFRA_PORTAL_TOKEN` secret in case they accidentally remove it some time
> OCPP gateway release shouldn't depend on openapi spec

- .github/workflows/pull-request-kover.yaml
- .github/workflows/pull-request.yaml
Make gradle `--parallel` parameter optional so that tests can be run sequentially if needed. It is enabled by default, so if left out, tests are run in parallel. That makes this change backwards-compatible to previous behavior where it was always enabled.
> feat: make running tests in parallel optional

- .github/workflows/sonar-cloud.yaml
Ensure the root level coverage task is run if it is available. This supports the kover and jacoco gradle plugins and won't run anything if none of them are available on the root module. 
Test run no longer complains its not able to find the report.xml: 
https://github.com/monta-app/library-kotlin/actions/runs/10680496631/job/29602037231
> feat(sonar): Ensure coverage task is run if present

- .github/workflows/monta-merge-command.yaml
- .github/workflows/production-pr.yaml
- .github/workflows/release-tag.yaml
- .github/workflows/staging-pr.yaml
- README.md
This PR introduces workflows to automate the creation of release pull requests for staging and production environments. Additionally, it includes a `monta-merge` command that automatic merge pull requests and triggers deployments for both staging and main branches.
This setup streamlines the release process and ensures that changes are efficiently promoted through the deployment pipeline, reducing manual effort.
The New Workflows:
-  `staging-pr` & `production-pr`: These workflows automate the creation of pull requests for promoting changes from develop to staging and from staging to main.
-   `monta-merge-commands`: This workflow handles the execution of the monta-merge command, automating the merging process for pull requests. It ensures that changes from develop are merged into …
> feat: incroduces workflows for auto-creating release PRs (PS-442)

- .github/workflows/monta-merge-command.yaml
This commits removes the if condition from monta merge command workflow to make the triggering of the monta-merge action configurable, we can rely on the if in the project workflow that calls it, as shown in the READEME.
> feat: remove if condition from monta-merge-command (PS-442)

- .github/workflows/deploy.yaml
The `more-power` input variable only have effect for self-hosted x86/arm64 runners. This updates the workflow so that it will also affect hosted runners, choosing `linux-x86-xl` for the powerful runner.
> feat: enable `more-power` input variable for github hosted deploys too

- .github/workflows/deploy.yaml
Many of our projects trigger production deploys when any tag is pushed. There is no check whatsoever if the tagged commit is actually part of the main branch.
This is a small safeguard against accidentally pushing a tag on another branch than the production release branch.
Somewhat tested here:
Check fails
https://github.com/monta-app/service-internal-auth/actions/runs/11069685675/job/30757756483
Check succeeds
https://github.com/monta-app/service-internal-auth/actions/runs/11069708249/job/30757824576
> feat(deploy): Restrict production deployments to main/master (PS-487)

- .github/workflows/it-test.yaml
Php has dropped the staging branch support, this PR changes the workflow to rely on the main branch instead.
> chore(it-test): use the main branch for the php server

- .github/workflows/deploy.yaml
There is an assumption that `OPENAPI_OUTPUT_DIR` is a prefix of `YML_FILE`. That is not the case if `YML_FILE` was found in a gradle subproject.
Example can be found [here](https://github.com/monta-app/service-grid/actions/runs/11275895966/job/31358811068#step:11:51).
Here, `YML_FILE` is `./grid/build/tmp/kapt3/classes/main/META-INF/swagger/grid.yml`, while `OPENAPI_OUTPUT_DIR` is `build/tmp/kapt3/classes/main/META-INF/swagger`.
If the assumption holds (which it does if there is only one gradle project and therefore a `/build` directory in the current working directory), things work, as the catalog file is then written to `build/tmp/kapt3/classes/main/META-INF/swagger/catalog_servicename_api.yaml` which is fine as the directory `build/tmp/kapt3/classes/main/META-INF/swagger/` already …
> fix(deploy): make openapi backstage upload work when yml exists in gradle subproject

- .github/workflows/it-test.yaml
Not entirely sure what changed the last weeks but our it-tests started to fail, after some investigation I noticed that the DB migrations and the seeding of the database was not happening automatically anymore.
Fix:
I've added an extra step to execute the migrations and seeding before starting the tests.
> Fix(it-test): Run migrations and seed database before it-tests

- .github/workflows/deploy.yaml
This will give a heads up in the #migration-deploys Slack channel that migration changes have been merged on some service that is going into production and will probably be synced in argocd soon or now if automatic.
The log in the slack channel can also be used to determine potentially applied migrations in case of incidents.
The match pattern is best effort for Flyway, trying to hit both single- and multi-service repos - or any *.sql file in general
```
with:
files: |
**/resources/db/migration/**
**/*.sql
```
Context: https://montaapp.atlassian.net/browse/SRE-732
> feat: Notify when migrations are being deployed

- .github/workflows/deploy.yaml
With continuous deploy, we don't run tests during deploy, because they have been run before merge of the PR into the trunk branch.
We need to parameterize whether to run tests or not in the deploy job from the outside to be able to use it for continuous deployment.
This PR introduces a parameter that allows for that control and keeps the default behavior for consumers that don't set the parameter.
When using `needs`, a default `if: success()` is added to the job, requiring dependencies to succeed. This can be circumvented using either `if: ! failure()` or more specifically `if: always() && needs.build.result == 'success' && needs.init.result == 'success' && (!inputs.run-tests || (inputs.run-tests && needs.test.result == 'success'))`.
I've chosen `!failure()` here to keep the complexity …
> feat: Run tests parameter

- .github/workflows/deploy.yaml
We are on v1.30 in both staging and production.
> chore(deploy): bump kubectl version to match the actual kubernetes version

- .github/workflows/deploy.yaml
We're seeing multiple push steps failing and succeeding in charges service (on staging), due to having concurrency control enabled, and `cancel-in-progress` enabled.
This change ensures that the steps that currently look at failure (where relevant), also makes sure that we haven't been cancelled.
This is very much just a reasonable search-replace by best effort.
> fix: don't push things if workflow got cancelled

- .github/workflows/deploy.yaml
* summary: `${{ ! failure() && ! cancelled() }}` = `${{ success() }}`
* also 'A default status check of success() is applied unless you include one of these functions'
* docs: [Status Check Functions](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#status-check-functions)
* followup on [PR#127](https://github.com/monta-app/github-workflows/pull/127)
> chore: Cleanup status check logic in `deploy.yaml`

- .github/workflows/deploy.yaml
Reverts monta-app/github-workflows#128
When tests are skipped, the push manifest + other steps that require tests aren't run
> revert: "chore: Cleanup status check logic in `deploy.yaml`"

- .github/workflows/deploy.yaml
a redo of the reverse of https://github.com/monta-app/github-workflows/pull/131 - just only where we can do it.
Alternatively we may remove the `needs` for the test step, which would probably be cleaner.
> chore: clean up if conditions again

- .github/workflows/allow-deploys.yml
- .github/workflows/block-deploys.yml
- .github/workflows/rollback.yml
- docs/workflow-guide.md
Wallet and PHP both have nice rollback workflows. This adds the simpler wallet version, made generic, but with the option to also block deploys when run.
Tested here: https://github.com/monta-app/service-openadr/actions/workflows/rollback.yml
See https://github.com/monta-app/service-openadr/pull/195/files for how to use.
> feat: add rollback workflow

- .github/workflows/deploy-kotlin.yml
The run-tests default does not seem to work correctly, this is an attempt at making it behave.
> fix: Add always() to run-tests conditional

- .github/workflows/component-service-profile-kotlin.yml
- .github/workflows/deploy-kotlin.yml
Add a new workflow that can be called from the deploy workflow and revives service profile generation. In order not to have to connect to teleport or headscale from github actions, we are taking the gitops route to push the generated service profile to kube-manifests.
In order to provide some flexibility, it's possible to change the service name after the file is created in case the deployed service has a different name than the standard {identifier}-{stage} pattern.
Test run: https://github.com/monta-app/service-search/actions/runs/17326632032/job/49192425139
Generated file: https://github.com/monta-app/kube-manifests/blob/main/apps/search/dev/app/templates/service-profile.yml
> feat(kotlin): Service profile generation for kotlin
